* Jirassic: A Jira Client for Emacs

Jirassic is an Emacs package that provides a convenient interface for interacting with Jira's REST API. It allows you to create, update, delete, and retrieve Jira issues directly from Emacs, with optional integration into Org Mode.

* Features
+ Serialize Jira issues into Org Mode entries.
+ Optional integration with ~org-roam~ for enhanced note-taking workflows.

* Installation

** Using ~use-package~ and ~elpaca~
#+begin_src emacs-lisp
  (use-package jirassic
    :ensure (:type git :host github :repo "emil-vdw/jirassic")
    :custom
    ;; Set your Jira host URL here
    (jirassic-host "https://your-subdomain.atlassian.net/"))
#+end_src

** Credentials
Jirassic uses Emacs' built-in ~auth-source~ library to securely manage your Jira credentials. Follow the steps below to configure your credentials.

*** Linux using ~authinfo~
1. *Locate or Create Your Auth Source File*
   On Linux, the default auth source file is typically located at `~/.authinfo` or `~/.authinfo.gpg`. If it doesn't exist, you can create one.

2. *Add Your Jira Credentials*
   Add an entry for your Jira instance in the auth source file. Replace ~host.atlassian.net~, ~<user-email>~, and ~<api-key>~ with your Jira host, email, and API key, respectively.

   #+BEGIN_SRC text
   machine host.atlassian.net login <user-email> password <api-key>
   #+END_SRC


3. *Verify Permissions*
   Ensure your auth source file has the correct permissions to prevent unauthorized access. For example:

   #+BEGIN_SRC shell
   chmod 600 ~/.authinfo
   #+END_SRC

4. *Test Your Configuration*
   After setting up your credentials, test the configuration by calling a Jirassic function, such as:

   #+BEGIN_SRC emacs-lisp
   (jirassic-get-issue "ISSUE-123")
   #+END_SRC

   If everything is configured correctly, Jirassic will use the credentials from your auth source file to authenticate with Jira.
   

*** Using Keychain on macOS
~auth-source~ can directly query the macOS Keychain for credentials. To add Jira credentials to the Keychain:
+ Open the Keychain Access application.
+ Create a new password entry with the following details:
  - *Key*: The Jira host (e.g., ~host.atlassian.net~).
  - *Account*: Your Jira email address.
  - *Password*: Your Jira API key.

* Usage

* Optional Features

* Dependencies
+ ~Emacs~ 29.3 or later
+ ~dash~ 2.0.0 or later
+ ~s~ 1.12.0 or later
+ ~org~ 9.5 or later

* License

Jirassic is licensed under the GNU General Public License v3.0. See the LICENSE file for details.
