name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: 30.1

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Lint
        run: make lint
